In [8]:
import pandas as pd 
import geopandas as gpd

In [9]:
mahalle_nufus = pd.read_excel(r"C:\Users\Monster\Desktop\CBS_CALISMALARI\getir_case_study\data\raw\bursa_mahalle_nufus.xls")
mahalle_nufus.head(10)

,Unnamed: 0,Unnamed: 1,Sütunlar
0,Satırlar,NaN,"Belediye, Köy Ve Mahalle Nüfusları"
1,NaN,NaN,Ölçüm bazında
2,NaN,NaN,NaN
3,NaN,NaN,NaN
4,2024,Bursa(Büyükorhan/Büyükorhan Bel./Akçasaz Mah.)...,152
5,NaN,Bursa(Büyükorhan/Büyükorhan Bel./Aktaş Mah.)-1...,391
6,NaN,Bursa(Büyükorhan/Büyükorhan Bel./Armutçuk Mah....,209
7,NaN,Bursa(Büyükorhan/Büyükorhan Bel./Bademlik Mah....,58
8,NaN,Bursa(Büyükorhan/Büyükorhan Bel./Balaban Mah.)...,262
9,NaN,Bursa(Büyükorhan/Büyükorhan Bel./Bayındır Mah....,88

In [10]:
mahalle_nufus = mahalle_nufus.dropna(subset=["Unnamed: 1", "Sütunlar"])
mahalle_nufus.head(10)

   Unnamed: 0                                         Unnamed: 1 Sütunlar
4        2024  Bursa(Büyükorhan/Büyükorhan Bel./Akçasaz Mah.)...      152
5         NaN  Bursa(Büyükorhan/Büyükorhan Bel./Aktaş Mah.)-1...      391
6         NaN  Bursa(Büyükorhan/Büyükorhan Bel./Armutçuk Mah....      209
7         NaN  Bursa(Büyükorhan/Büyükorhan Bel./Bademlik Mah....       58
8         NaN  Bursa(Büyükorhan/Büyükorhan Bel./Balaban Mah.)...      262
9         NaN  Bursa(Büyükorhan/Büyükorhan Bel./Bayındır Mah....       88
10        NaN  Bursa(Büyükorhan/Büyükorhan Bel./Burunca Mah.)...      115
11        NaN  Bursa(Büyükorhan/Büyükorhan Bel./Çakıryenice M...       76
12        NaN  Bursa(Büyükorhan/Büyükorhan Bel./Çeribaşı Mah....      227
13        NaN  Bursa(Büyükorhan/Büyükorhan Bel./Cumhuriyet Ma...      421

In [ ]:
mahalle_nufus = mahalle_nufus[~mahalle_nufus["Unnamed: 1"].str.contains("Belediye|Satırlar|Ölçüm", na=False)]

In [12]:
mahalle_nufus = mahalle_nufus.rename(columns={"Unnamed: 1": "adres", "Sütunlar": "nufus", "Unnamed: 0": "yil"})

In [13]:
mahalle_nufus["mahalle"] = mahalle_nufus["adres"].str.extract(r"/([^/]+ Mah\.)")[0].str.replace(" Mah.", "", regex=False)
mahalle_nufus.head()

    yil                                              adres nufus   mahalle
4  2024  Bursa(Büyükorhan/Büyükorhan Bel./Akçasaz Mah.)...   152   Akçasaz
5   NaN  Bursa(Büyükorhan/Büyükorhan Bel./Aktaş Mah.)-1...   391     Aktaş
6   NaN  Bursa(Büyükorhan/Büyükorhan Bel./Armutçuk Mah....   209  Armutçuk
7   NaN  Bursa(Büyükorhan/Büyükorhan Bel./Bademlik Mah....    58  Bademlik
8   NaN  Bursa(Büyükorhan/Büyükorhan Bel./Balaban Mah.)...   262   Balaban

In [ ]:

mahalle_nufus["ilce"] = mahalle_nufus["adres"].str.extract(r"Bursa\(([^/]+)")
mahalle_nufus["il"] = "Bursa"
mahalle_nufus["nufus"] = mahalle_nufus["nufus"].astype(int)
mahalle_nufus['yil'] = 2024
mahalle_nufus["yil"] = mahalle_nufus["yil"].astype(int)
mahalle_nufus.head()

,yil,adres,nufus,mahalle,mahalle_kodu,ilce,il
4,2024,Bursa(Büyükorhan/Büyükorhan Bel./Akçasaz Mah.)...,152,Akçasaz,NaN,Büyükorhan,Bursa
5,2024,Bursa(Büyükorhan/Büyükorhan Bel./Aktaş Mah.)-1...,391,Aktaş,NaN,Büyükorhan,Bursa
6,2024,Bursa(Büyükorhan/Büyükorhan Bel./Armutçuk Mah....,209,Armutçuk,NaN,Büyükorhan,Bursa
7,2024,Bursa(Büyükorhan/Büyükorhan Bel./Bademlik Mah....,58,Bademlik,NaN,Büyükorhan,Bursa
8,2024,Bursa(Büyükorhan/Büyükorhan Bel./Balaban Mah.)...,262,Balaban,NaN,Büyükorhan,Bursa

In [15]:
mahalle_nufus["mahalle_kodu"] = mahalle_nufus["adres"].str.extract(r"[-](\d+)$")
mahalle_nufus.head()

,yil,adres,nufus,mahalle,mahalle_kodu,ilce,il
4,2024,Bursa(Büyükorhan/Büyükorhan Bel./Akçasaz Mah.)...,152,Akçasaz,183537,Büyükorhan,Bursa
5,2024,Bursa(Büyükorhan/Büyükorhan Bel./Aktaş Mah.)-1...,391,Aktaş,183539,Büyükorhan,Bursa
6,2024,Bursa(Büyükorhan/Büyükorhan Bel./Armutçuk Mah....,209,Armutçuk,11335,Büyükorhan,Bursa
7,2024,Bursa(Büyükorhan/Büyükorhan Bel./Bademlik Mah....,58,Bademlik,183605,Büyükorhan,Bursa
8,2024,Bursa(Büyükorhan/Büyükorhan Bel./Balaban Mah.)...,262,Balaban,183541,Büyükorhan,Bursa

In [16]:
mahalle_nufus["mahalle"] = mahalle_nufus["mahalle"].str.strip()
mahalle_nufus["mahalle_kodu"] = mahalle_nufus["mahalle_kodu"].str.strip().astype(int)
mahalle_nufus.head()

,yil,adres,nufus,mahalle,mahalle_kodu,ilce,il
4,2024,Bursa(Büyükorhan/Büyükorhan Bel./Akçasaz Mah.)...,152,Akçasaz,183537,Büyükorhan,Bursa
5,2024,Bursa(Büyükorhan/Büyükorhan Bel./Aktaş Mah.)-1...,391,Aktaş,183539,Büyükorhan,Bursa
6,2024,Bursa(Büyükorhan/Büyükorhan Bel./Armutçuk Mah....,209,Armutçuk,11335,Büyükorhan,Bursa
7,2024,Bursa(Büyükorhan/Büyükorhan Bel./Bademlik Mah....,58,Bademlik,183605,Büyükorhan,Bursa
8,2024,Bursa(Büyükorhan/Büyükorhan Bel./Balaban Mah.)...,262,Balaban,183541,Büyükorhan,Bursa

In [23]:
mahalle_nufus = mahalle_nufus[['yil', 'adres', 'il', 'ilce', 'mahalle', 'mahalle_kodu', 'nufus']]
mahalle_nufus.head()

,yil,adres,il,ilce,mahalle,mahalle_kodu,nufus
4,2024,Bursa(Büyükorhan/Büyükorhan Bel./Akçasaz Mah.)...,Bursa,Büyükorhan,Akçasaz,183537,152
5,2024,Bursa(Büyükorhan/Büyükorhan Bel./Aktaş Mah.)-1...,Bursa,Büyükorhan,Aktaş,183539,391
6,2024,Bursa(Büyükorhan/Büyükorhan Bel./Armutçuk Mah....,Bursa,Büyükorhan,Armutçuk,11335,209
7,2024,Bursa(Büyükorhan/Büyükorhan Bel./Bademlik Mah....,Bursa,Büyükorhan,Bademlik,183605,58
8,2024,Bursa(Büyükorhan/Büyükorhan Bel./Balaban Mah.)...,Bursa,Büyükorhan,Balaban,183541,262

In [99]:
mahalle_nufus.to_csv(r"C:\Users\Monster\Desktop\CBS_CALISMALARI\getir_case_study\data\processed\mahalle_nufus_duzenli.csv", index=False, encoding="utf-8-sig")

In [20]:
ilce_nufus = pd.read_excel(r"C:\Users\Monster\Desktop\CBS_CALISMALARI\getir_case_study\data\raw\bursa_ilce_nufus.xls")
ilce_nufus.head(10)

,Unnamed: 0,Unnamed: 1,Sütunlar
0,Satırlar,NaN,"Belediye, Köy Ve Mahalle Nüfusları"
1,NaN,NaN,Ölçüm bazında
2,NaN,NaN,NaN
3,NaN,NaN,NaN
4,2024,Bursa(Büyükorhan/Büyükorhan Bel.)-1544,9596
5,NaN,Bursa(Gemlik/Gemlik Bel.)-1543,123361
6,NaN,Bursa(Gürsu/Gürsu Bel.)-1542,104867
7,NaN,Bursa(Harmancık/Harmancık Bel.)-1541,6204
8,NaN,Bursa(İnegöl/İnegöl Bel.)-1540,302251
9,NaN,Bursa(İznik/İznik Bel.)-1531,45208

In [21]:
ilce_nufus = ilce_nufus[~ilce_nufus["Unnamed: 1"].str.contains("Belediye|Satırlar|Ölçüm", na=False)]
ilce_nufus = ilce_nufus.dropna(subset=["Unnamed: 1", "Sütunlar"])
ilce_nufus = ilce_nufus.rename(columns={"Unnamed: 1": "adres", "Sütunlar": "nufus", "Unnamed: 0": "yil"})
ilce_nufus["il"] = "Bursa"
ilce_nufus["yil"] = 2024
ilce_nufus["ilce"] = ilce_nufus["adres"].str.extract(r"Bursa\(([^/]+)")
ilce_nufus["ilce_kodu"] = ilce_nufus["adres"].str.extract(r"-(\d+)")
ilce_nufus.head()

,yil,adres,nufus,il,ilce,ilce_kodu
4,2024,Bursa(Büyükorhan/Büyükorhan Bel.)-1544,9596,Bursa,Büyükorhan,1544
5,2024,Bursa(Gemlik/Gemlik Bel.)-1543,123361,Bursa,Gemlik,1543
6,2024,Bursa(Gürsu/Gürsu Bel.)-1542,104867,Bursa,Gürsu,1542
7,2024,Bursa(Harmancık/Harmancık Bel.)-1541,6204,Bursa,Harmancık,1541
8,2024,Bursa(İnegöl/İnegöl Bel.)-1540,302251,Bursa,İnegöl,1540

In [22]:
ilce_nufus["ilce"] = ilce_nufus["ilce"].str.strip()
ilce_nufus["ilce_kodu"] = ilce_nufus["ilce_kodu"].str.strip().astype(int)
ilce_nufus["nufus"] = ilce_nufus["nufus"].astype(int)

In [24]:
ilce_nufus = ilce_nufus[['yil', 'adres', 'il', 'ilce', 'ilce_kodu', 'nufus']]
ilce_nufus.head()

,yil,adres,il,ilce,ilce_kodu,nufus
4,2024,Bursa(Büyükorhan/Büyükorhan Bel.)-1544,Bursa,Büyükorhan,1544,9596
5,2024,Bursa(Gemlik/Gemlik Bel.)-1543,Bursa,Gemlik,1543,123361
6,2024,Bursa(Gürsu/Gürsu Bel.)-1542,Bursa,Gürsu,1542,104867
7,2024,Bursa(Harmancık/Harmancık Bel.)-1541,Bursa,Harmancık,1541,6204
8,2024,Bursa(İnegöl/İnegöl Bel.)-1540,Bursa,İnegöl,1540,302251

In [98]:
ilce_nufus.to_csv(r"C:\Users\Monster\Desktop\CBS_CALISMALARI\getir_case_study\data\processed\ilce_nufus_duzenli.csv", index=False, encoding="utf-8-sig")

In [45]:
import geopandas as gpd 
mahalle_sinir = gpd.read_file(r"C:\Users\Monster\Desktop\CBS_CALISMALARI\getir_case_study\data\raw\bursa_mahalle.geojson")
mahalle_sinir.head()

,id,OBJECTID,ID,AD,KIMLIKNO,BELDEID,ILCEID,BELEDIYEID,GLOBALID,OLUSTURMATARIHI,...,OLUSTURAN,DEGISTIREN,OPERATIONNUMBER,OPERATIONDESCRIPTION,TANITIMKODU,VERIKAYNAGI,SE_ANNO_CAD_DATA,SHAPE_Length,SHAPE_Area,geometry
0,mahalle.fid--6600e34d_1990594e2c7_-7bdd,36622,{E72E41EC-8433-4EE0-96B1-2F4CB3EC9CD9},HAMZABEY OSB,196689,None,{9348171B-682E-44EC-AE55-2A64BBF9B0E5},None,{0315AE70-419C-493A-82F7-8409A0FEA63E},2020-02-03 11:35:08+00:00,...,None,None,NaN,MAKS YAYGINLASTIRMA PROJESİ KAPSAMINDA 17.02.2...,117,13.0,None,16339.996397,4.198187e+06,"MULTIPOLYGON (((29.55137 40.16498, 29.55178 40..."
1,mahalle.fid--6600e34d_1990594e2c7_-7bdc,36623,{A8B4C636-27CC-47CB-8DBD-233EAABDCE20},SÜLEYMANİYEOSB,11395,None,{9348171B-682E-44EC-AE55-2A64BBF9B0E5},None,{15AC1D3D-726B-4179-B68C-C4090F453C73},2020-02-04 11:56:23+00:00,...,None,None,NaN,MAKS YAYGINLASTIRMA PROJESİ KAPSAMINDA 17.02.2...,118,13.0,None,8795.640002,2.846059e+06,"MULTIPOLYGON (((29.50968 40.09145, 29.51127 40..."
2,mahalle.fid--6600e34d_1990594e2c7_-7bdb,36624,{51E1961A-413D-45AF-A167-6B9878D0C63F},MİNARELİÇAVUŞOSB,11110,None,{A8D46685-15A5-4B18-A42E-AE843A2ECB71},None,{C9B0464C-208B-4F6E-B7CE-5F5E5B13A11D},2020-01-31 11:52:09+00:00,...,None,None,7.0,SINIR KIRIK EKLEME,71,NaN,None,7830.875428,2.242865e+06,"MULTIPOLYGON (((28.93553 40.24016, 28.93535 40..."
3,mahalle.fid--6600e34d_1990594e2c7_-7bda,36635,{D134606E-0D70-4C27-BB3F-20203E184F07},CANBAZLARKÖYÜ,183645,None,{80E88AF7-448C-4167-8039-9203E9B218BF},{A4725E60-4083-452F-BABE-3483451B1C07},{81CC776F-2FD7-4199-8586-9C2EDA6555A0},2020-01-31 07:44:32+00:00,...,None,None,NaN,MAKS YAYGINLASTIRMA PROJESİ KAPSAMINDA 18.02.2...,9,2.0,None,8908.084755,3.298844e+06,"MULTIPOLYGON (((29.17841 40.25375, 29.18629 40..."
4,mahalle.fid--6600e34d_1990594e2c7_-7bd9,36632,{04226B72-0DC2-4A18-A3A3-429EFAF28480},İSTİKLAL,11362,None,{80E88AF7-448C-4167-8039-9203E9B218BF},{A4725E60-4083-452F-BABE-3483451B1C07},{F3195C68-474C-4E40-824D-BF1DF62F19B4},2020-01-31 07:44:32+00:00,...,None,None,1.0,SINIR KIRIK EKLEME,2,NaN,None,11178.494231,3.909006e+06,"MULTIPOLYGON (((29.20925 40.22543, 29.20998 40..."

In [46]:
mahalle_sinir = mahalle_sinir[["AD", "KIMLIKNO", "SHAPE_Length", "SHAPE_Area", "geometry"]]
mahalle_sinir = mahalle_sinir.rename(columns={
    "AD": "mahalle",
    "KIMLIKNO": "mahalle_kodu",
    "SHAPE_Length": "uzunluk",
    "SHAPE_Area": "alan"
})

mahalle_sinir["il"] = "Bursa"
mahalle_sinir.head()

,mahalle,mahalle_kodu,uzunluk,alan,geometry,il
0,HAMZABEY OSB,196689,16339.996397,4.198187e+06,"MULTIPOLYGON (((29.55137 40.16498, 29.55178 40...",Bursa
1,SÜLEYMANİYEOSB,11395,8795.640002,2.846059e+06,"MULTIPOLYGON (((29.50968 40.09145, 29.51127 40...",Bursa
2,MİNARELİÇAVUŞOSB,11110,7830.875428,2.242865e+06,"MULTIPOLYGON (((28.93553 40.24016, 28.93535 40...",Bursa
3,CANBAZLARKÖYÜ,183645,8908.084755,3.298844e+06,"MULTIPOLYGON (((29.17841 40.25375, 29.18629 40...",Bursa
4,İSTİKLAL,11362,11178.494231,3.909006e+06,"MULTIPOLYGON (((29.20925 40.22543, 29.20998 40...",Bursa

In [47]:
mahalle_sinir.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [48]:
mahalle_sinir_crs = mahalle_sinir.to_crs("EPSG:5254")
mahalle_sinir["alan_5254"] = mahalle_sinir_crs.geometry.area
mahalle_sinir = mahalle_sinir[['il', 'mahalle', 'mahalle_kodu', 'uzunluk', 'alan','alan_5254','geometry']]
mahalle_sinir.head()

,il,mahalle,mahalle_kodu,uzunluk,alan,alan_5254,geometry
0,Bursa,HAMZABEY OSB,196689,16339.996397,4.198187e+06,4.198131e+06,"MULTIPOLYGON (((29.55137 40.16498, 29.55178 40..."
1,Bursa,SÜLEYMANİYEOSB,11395,8795.640002,2.846059e+06,2.846020e+06,"MULTIPOLYGON (((29.50968 40.09145, 29.51127 40..."
2,Bursa,MİNARELİÇAVUŞOSB,11110,7830.875428,2.242865e+06,2.242835e+06,"MULTIPOLYGON (((28.93553 40.24016, 28.93535 40..."
3,Bursa,CANBAZLARKÖYÜ,183645,8908.084755,3.298844e+06,3.298800e+06,"MULTIPOLYGON (((29.17841 40.25375, 29.18629 40..."
4,Bursa,İSTİKLAL,11362,11178.494231,3.909006e+06,3.908954e+06,"MULTIPOLYGON (((29.20925 40.22543, 29.20998 40..."

In [106]:
mahalle_sinir.to_file(r"C:\Users\Monster\Desktop\CBS_CALISMALARI\getir_case_study\data\processed\mahalle_sinir_duzenli.geojson", driver="GeoJSON")

In [54]:
ilce_sinir = gpd.read_file(r"C:\Users\Monster\Desktop\CBS_CALISMALARI\getir_case_study\data\raw\bursa_ilce.geojson")
ilce_sinir.head()

,id,OBJECTID,ID,AD,KIMLIKNO,ILID,GLOBALID,OLUSTURMATARIHI,DEGISTIRMETARIHI,GECERLILIKTARIHI,...,MERKEZILCEMI,OLUSTURAN,DEGISTIREN,OPERATIONNUMBER,OPERATIONDESCRIPTION,UAVTMERKEZKOYKODU,UAVTMERKEZBUCAKKODU,VERIKAYNAGI,SE_ANNO_CAD_DATA,geometry
0,ILCE.fid--6600e34d_1990594e2c7_-77ab,15629,{A8D46685-15A5-4B18-A42E-AE843A2ECB71},NİLÜFER,1829,{4A26CEC8-8CBF-4D1F-BAE5-7C2311FA22CD},{6B8E1736-D366-4E5B-AFCA-00144F13914E},2020-01-31 11:52:09+00:00,NaT,None,...,1,NaN,36739523862,NaN,MAKS YAYGINLASTIRMA PROJESİ KAPSAMINDA 17.02.2...,7291,349,2,None,"MULTIPOLYGON (((28.74359 40.29972, 28.7422 40...."
1,ILCE.fid--6600e34d_1990594e2c7_-77aa,15630,{80E88AF7-448C-4167-8039-9203E9B218BF},GÜRSU,1935,{4A26CEC8-8CBF-4D1F-BAE5-7C2311FA22CD},{FB353FF2-964D-456F-8CD3-D66DC3F66A89},2020-01-31 07:44:32+00:00,NaT,None,...,1,NaN,31571217108,NaN,MAKS YAYGINLASTIRMA PROJESİ KAPSAMINDA 18.02.2...,7415,355,2,None,"MULTIPOLYGON (((29.29997 40.33747, 29.30033 40..."
2,ILCE.fid--6600e34d_1990594e2c7_-77a9,15631,{F5760BFA-94E9-4163-92D3-F43F8E39AF56},GEMLİK,1343,{4A26CEC8-8CBF-4D1F-BAE5-7C2311FA22CD},{101E374B-B569-4D6F-AD69-965570C5634B},2017-05-12 21:00:00+00:00,2020-02-29 06:50:57+00:00,None,...,2,4.594920e+10,17701859660,446.0,MAKS YAYGINLASTIRMA PROJESİ KAPSAMINDA 12.05.2...,7394,354,2,None,"MULTIPOLYGON (((29.06071 40.56103, 29.06029 40..."
3,ILCE.fid--6600e34d_1990594e2c7_-77a8,15632,{E2FE8A2C-AD97-4C88-A591-9F8B53090719},KESTEL,1960,{4A26CEC8-8CBF-4D1F-BAE5-7C2311FA22CD},{4CD61902-DBF5-41FB-8677-937F7C4CCCCE},2021-06-03 09:46:07+00:00,NaT,None,...,2,NaN,31571217108,NaN,MAKS YAYGINLASTIRMA PROJESİ KAPSAMINDA 23.06.2...,7684,362,2,None,"MULTIPOLYGON (((29.32909 40.31779, 29.32435 40..."
4,ILCE.fid--6600e34d_1990594e2c7_-77a7,15633,{2B77DEE0-31CD-460E-8340-5DBD1F096A65},MUSTAFAKEMALPAŞA,1535,{4A26CEC8-8CBF-4D1F-BAE5-7C2311FA22CD},{695F1478-1DC7-49D6-92DB-6A20AE6C96DA},2021-06-08 21:00:00+00:00,NaT,None,...,2,NaN,16241714590,NaN,MAKS YAYGINLASTIRMA PROJESİ KAPSAMINDA 24.06.2...,7750,365,2,None,"MULTIPOLYGON (((28.4744 40.1865, 28.47281 40.1..."

In [55]:
ilce_sinir = ilce_sinir[["AD", "KIMLIKNO", "geometry"]]
ilce_sinir = ilce_sinir.rename(columns={
    "AD": "ilce",
    "KIMLIKNO": "ilce_kodu"
})

ilce_sinir["il"] = "Bursa"

In [56]:
ilce_sinir_crs = ilce_sinir.to_crs("EPSG:5254")
ilce_sinir["alan_5254"] = ilce_sinir_crs.geometry.area

In [58]:
ilce_sinir = ilce_sinir[['il', 'ilce', 'ilce_kodu', 'alan_5254', 'geometry']]

ilce_sinir.head()

,il,ilce,ilce_kodu,alan_5254,geometry
0,Bursa,NİLÜFER,1829,5.067293e+08,"MULTIPOLYGON (((28.74359 40.29972, 28.7422 40...."
1,Bursa,GÜRSU,1935,1.186441e+08,"MULTIPOLYGON (((29.29997 40.33747, 29.30033 40..."
2,Bursa,GEMLİK,1343,4.101771e+08,"MULTIPOLYGON (((29.06071 40.56103, 29.06029 40..."
3,Bursa,KESTEL,1960,3.907537e+08,"MULTIPOLYGON (((29.32909 40.31779, 29.32435 40..."
4,Bursa,MUSTAFAKEMALPAŞA,1535,1.567995e+09,"MULTIPOLYGON (((28.4744 40.1865, 28.47281 40.1..."

In [105]:
ilce_sinir.to_file(r"C:\Users\Monster\Desktop\CBS_CALISMALARI\getir_case_study\data\processed\ilce_sinir_duzenli.geojson", driver="GeoJSON")

In [87]:
ilce_yas = pd.read_excel(r"C:\Users\Monster\Desktop\CBS_CALISMALARI\getir_case_study\data\raw\bursa_ilce_yas_dagilimi.xls")
ilce_yas.head(10)

,Unnamed: 0,Unnamed: 1,Sütunlar,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20
0,Satırlar,NaN,"İbbs-Düzey1, İbbs-Düzey2, İl Ve İlçe Nüfusları",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,0-4,10-14,15-19,20-24,25-29,30-34,35-39,40-44,...,50-54,55-59,5-9,60-64,65-69,70-74,75-79,80-84,85-89,90+
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024,Bursa(Büyükorhan)-1783,310,341,527,535,549,420,437,526,...,742,741,304,898,875,724,591,345,128,68
5,NaN,Bursa(Gemlik)-1343,6127,8023,7721,7589,8809,8947,9110,10094,...,8670,7554,7852,7191,6226,4546,2902,1573,807,311
6,NaN,Bursa(Gürsu)-1935,6894,8821,7988,7057,8028,8393,8809,8498,...,6406,5261,8922,4933,3484,2146,1204,664,336,151
7,NaN,Bursa(Harmancık)-1799,201,236,284,299,351,310,325,331,...,385,511,203,636,628,456,348,231,92,35
8,NaN,Bursa(İnegöl)-1411,20199,24281,22354,20465,24119,22795,23269,23514,...,19374,15901,25075,13867,10367,6968,4549,2684,1201,500
9,NaN,Bursa(İznik)-1420,1954,2657,2545,2504,2927,2713,2848,3283,...,3504,3352,2564,3279,2797,2072,1441,901,424,186

In [88]:
ilce_yas.columns = ilce_yas.iloc[1]

ilce_yas.columns = ilce_yas.columns.str.replace("-", "_")

ilce_yas.head()

1,NaN,NaN,0_4,10_14,15_19,20_24,25_29,30_34,35_39,40_44,...,50_54,55_59,5_9,60_64,65_69,70_74,75_79,80_84,85_89,90+
0,Satırlar,NaN,"İbbs-Düzey1, İbbs-Düzey2, İl Ve İlçe Nüfusları",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,0-4,10-14,15-19,20-24,25-29,30-34,35-39,40-44,...,50-54,55-59,5-9,60-64,65-69,70-74,75-79,80-84,85-89,90+
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024,Bursa(Büyükorhan)-1783,310,341,527,535,549,420,437,526,...,742,741,304,898,875,724,591,345,128,68

In [89]:
nan_indices = [i for i, col in enumerate(ilce_yas.columns) if pd.isna(col)]


if len(nan_indices) >= 2:
    ilce_yas.columns.values[nan_indices[0]] = "yil"
    ilce_yas.columns.values[nan_indices[1]] = "adres"

In [90]:
ilce_yas.head()

1,yil,adres,0_4,10_14,15_19,20_24,25_29,30_34,35_39,40_44,...,50_54,55_59,5_9,60_64,65_69,70_74,75_79,80_84,85_89,90+
0,Satırlar,NaN,"İbbs-Düzey1, İbbs-Düzey2, İl Ve İlçe Nüfusları",NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,0-4,10-14,15-19,20-24,25-29,30-34,35-39,40-44,...,50-54,55-59,5-9,60-64,65-69,70-74,75-79,80-84,85-89,90+
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2024,Bursa(Büyükorhan)-1783,310,341,527,535,549,420,437,526,...,742,741,304,898,875,724,591,345,128,68

In [91]:
ilce_yas = ilce_yas.iloc[4:].reset_index(drop=True)
ilce_yas.head()

1,yil,adres,0_4,10_14,15_19,20_24,25_29,30_34,35_39,40_44,...,50_54,55_59,5_9,60_64,65_69,70_74,75_79,80_84,85_89,90+
0,2024,Bursa(Büyükorhan)-1783,310,341,527,535,549,420,437,526,...,742,741,304,898,875,724,591,345,128,68
1,NaN,Bursa(Gemlik)-1343,6127,8023,7721,7589,8809,8947,9110,10094,...,8670,7554,7852,7191,6226,4546,2902,1573,807,311
2,NaN,Bursa(Gürsu)-1935,6894,8821,7988,7057,8028,8393,8809,8498,...,6406,5261,8922,4933,3484,2146,1204,664,336,151
3,NaN,Bursa(Harmancık)-1799,201,236,284,299,351,310,325,331,...,385,511,203,636,628,456,348,231,92,35
4,NaN,Bursa(İnegöl)-1411,20199,24281,22354,20465,24119,22795,23269,23514,...,19374,15901,25075,13867,10367,6968,4549,2684,1201,500

In [92]:
ilce_yas["ilce"] = ilce_yas["adres"].str.extract(r"\((.*?)\)")
ilce_yas["ilce_kodu"] = ilce_yas["adres"].str.extract(r"-(\d+)")
ilce_yas["ilce"] = ilce_yas["ilce"].str.strip()
ilce_yas["ilce_kodu"] = ilce_yas["ilce_kodu"].str.strip().astype(int)
ilce_yas['yil'] = 2024


ilce_yas.head()

1,yil,adres,0_4,10_14,15_19,20_24,25_29,30_34,35_39,40_44,...,5_9,60_64,65_69,70_74,75_79,80_84,85_89,90+,ilce,ilce_kodu
0,2024,Bursa(Büyükorhan)-1783,310,341,527,535,549,420,437,526,...,304,898,875,724,591,345,128,68,Büyükorhan,1783
1,2024,Bursa(Gemlik)-1343,6127,8023,7721,7589,8809,8947,9110,10094,...,7852,7191,6226,4546,2902,1573,807,311,Gemlik,1343
2,2024,Bursa(Gürsu)-1935,6894,8821,7988,7057,8028,8393,8809,8498,...,8922,4933,3484,2146,1204,664,336,151,Gürsu,1935
3,2024,Bursa(Harmancık)-1799,201,236,284,299,351,310,325,331,...,203,636,628,456,348,231,92,35,Harmancık,1799
4,2024,Bursa(İnegöl)-1411,20199,24281,22354,20465,24119,22795,23269,23514,...,25075,13867,10367,6968,4549,2684,1201,500,İnegöl,1411

In [93]:
ilce_yas["yas_0_14"] = ilce_yas[["0_4", "5_9", "10_14"]].sum(axis=1)
ilce_yas["yas_15_24"] = ilce_yas[["15_19", "20_24"]].sum(axis=1)
ilce_yas["yas_25_34"] = ilce_yas[["25_29", "30_34"]].sum(axis=1)
ilce_yas["yas_35_49"] = ilce_yas[["35_39", "40_44", "45_49"]].sum(axis=1)
ilce_yas["yas_50_64"] = ilce_yas[["50_54", "55_59", "60_64"]].sum(axis=1)
ilce_yas["yas_65_plus"] = ilce_yas[["65_69", "70_74", "75_79", "80_84", "85_89", "90+"]].sum(axis=1)

yas_sutunlari = ["0_4", "5_9", "10_14", "15_19", "20_24", "25_29", "30_34", "35_39", "40_44",
                 "45_49", "50_54", "55_59", "60_64", "65_69", "70_74", "75_79", "80_84", "85_89", "90+"]
ilce_yas = ilce_yas.drop(columns=yas_sutunlari)

ilce_yas.head()

1,yil,adres,ilce,ilce_kodu,yas_0_14,yas_15_24,yas_25_34,yas_35_49,yas_50_64,yas_65_plus
0,2024,Bursa(Büyükorhan)-1783,Büyükorhan,1783,955,1062,969,1498,2381,2731
1,2024,Bursa(Gemlik)-1343,Gemlik,1343,22002,15310,17756,28513,23415,16365
2,2024,Bursa(Gürsu)-1935,Gürsu,1935,24637,15045,16421,24179,16600,7985
3,2024,Bursa(Harmancık)-1799,Harmancık,1799,640,583,661,998,1532,1790
4,2024,Bursa(İnegöl)-1411,İnegöl,1411,69555,42819,46914,67552,49142,26269

In [94]:
ilce_yas["il"] = "Bursa"
ilce_yas["tum_yas_toplam"] = ilce_yas[
    ["yas_0_14", "yas_15_24", "yas_25_34", "yas_35_49", "yas_50_64", "yas_65_plus"]
    ].sum(axis=1)
ilce_yas = ilce_yas[['yil', 'adres', 'il', 'ilce', 'ilce_kodu', "yas_0_14","yas_15_24","yas_25_34","yas_35_49","yas_50_64","yas_65_plus","tum_yas_toplam"]]
ilce_yas.head()

1,yil,adres,il,ilce,ilce_kodu,yas_0_14,yas_15_24,yas_25_34,yas_35_49,yas_50_64,yas_65_plus,tum_yas_toplam
0,2024,Bursa(Büyükorhan)-1783,Bursa,Büyükorhan,1783,955,1062,969,1498,2381,2731,9596
1,2024,Bursa(Gemlik)-1343,Bursa,Gemlik,1343,22002,15310,17756,28513,23415,16365,123361
2,2024,Bursa(Gürsu)-1935,Bursa,Gürsu,1935,24637,15045,16421,24179,16600,7985,104867
3,2024,Bursa(Harmancık)-1799,Bursa,Harmancık,1799,640,583,661,998,1532,1790,6204
4,2024,Bursa(İnegöl)-1411,Bursa,İnegöl,1411,69555,42819,46914,67552,49142,26269,302251

In [95]:
ilce_yas.to_csv(r"C:\Users\Monster\Desktop\CBS_CALISMALARI\getir_case_study\data\processed\ilce_yas_duzenli.csv", index=False, encoding="utf-8-sig")

In [100]:
ilce_ses = pd.read_csv(r"C:\Users\Monster\Desktop\CBS_CALISMALARI\getir_case_study\data\raw\bursa_ses.csv")
ilce_ses.head()

      il       ilce  ses_skoru
0  Bursa    Nilüfer        166
1  Bursa    Mudanya        138
2  Bursa  Osmangazi        136
3  Bursa     Kestel        133
4  Bursa   Yıldırım        130

In [101]:
ilce_ses.to_csv(r"C:\Users\Monster\Desktop\CBS_CALISMALARI\getir_case_study\data\processed\ilce_ses_duzenli.csv", index=False, encoding="utf-8-sig")

In [107]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Monster\Desktop\CBS_CALISMALARI\getir_case_study\data\raw\siparis.csv")
df2= pd.read_csv(r"C:\Users\Monster\Desktop\CBS_CALISMALARI\getir_case_study\data\raw\warehouse.csv")

gdf = gpd.GeoDataFrame(df, geometry=gpd.points_from_xy(df["longitude"],df["latitude"]), crs="EPSG:4326")
gdf2 = gpd.GeoDataFrame(df2, geometry=gpd.points_from_xy(df2["Longitude"],df2["Latitude"]),crs="EPSG:4326")

gdf.to_file(r"C:\Users\Monster\Desktop\CBS_CALISMALARI\getir_case_study\data\processed\siparis.geojson", driver="GeoJSON")
gdf2.to_file(r"C:\Users\Monster\Desktop\CBS_CALISMALARI\getir_case_study\data\processed\warehouse.geojson", driver="GeoJSON")